# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:

concurrency:
  group: release-main
  cancel-in-progress: false

jobs:
  release:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    permissions: # semantic-release가 릴리스/태그/커밋 푸시 가능하도록
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 전체 히스토리/태그 필요(버전 계산)
          persist-credentials: false # 기본 GITHUB_TOKEN 제거

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm test --if-present

      - name: Release (semantic-release)
        run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }} # semantic-release가 우선적으로 참조
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} # 일부 플러그인들이 GITHUB_TOKEN만 봄
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
